### ISSUE TITLE
The performance is much lower than results in the original paper

### ISSUE THREAD

**Issue by Tianhao-Peng** [GitEventhandler/H2GCN-PyTorch#3]
I have read the closed issues in this repo, and we all meet the problem that the performance is much lower than the results in the original paper. You said the key problem is the hyper-parameters. Could you please provide the best hyper-parameters of the datasets ( especially Chameleon and Squirrel)?

Thank you!

**Comment by GitEventhandler** [comment]
Acknowledged, I will update this repo after tuning hyper parameters for standard datasets.

**Comment by GitEventhandler** [comment]
Fixed.
